query_1="CREATE TABLE Readers(id serial PRIMARY KEY, name VARCHAR(60), email VARCHAR(60) UNIQUE, is_active BIT NOT NULL 1);"
query_3="CREATE TABLE Books(id serial PRIMARY KEY, title VARCHAR(60), PRICE DECIMAL(5,2), author VARCHAR(60), publishing_houses_id INT, FOREIGN KEY(publishing_houses_id) REFERENCES PublishingHouses(id));"
query_2="CREATE TABLE PublishingHouses(id serial PRIMARY KEY, name VARCHAR(60), city VARCHAR(20), adress VARCHAR(120));"
query_4="CREATE TABLE reader_books(id serial PRIMARY KEY, reader_id INT, book_id INT, FOREIGN KEY(reader_id)REFERENCES Readers(id), FOREIGN KEY(book_id) REFERENCES Books(id));"
query_5="SELECT * FROM Books WHERE Books.price>10 "
query_6="INSERT INTO PublishingHouses(name,city,adress) VALUES('Super Books', 'Wilderness', '120 Maine Road')"
query_7="DELETE FROM Books WHERE Books.id=12"
query_8="SELECT Readers.name FROM Readers  JOIN reader_book ON Readers.id=reader_book.reader_id"
query_9="UPDATE Readers SET Readers.is_active=0 WHERE Readers.id=2;"
query_10="ALTER TABLE Readers ADD date_of_birth TIMESTAMP"